### ISSUE TITLE
@provide type members

### ISSUE THREAD

**Issue by mauhiz** [lloydmeta/provide#2]
```
trait Parent { type A }
trait Child { @provide type A = String }
```

should compile

**Comment by lloydmeta** [comment]
Good idea. 

That said, using the `override` keyword seems to do the same thing as `@provide` would, since you can't actually override type members.

``` scala
trait A {
  type B
}

trait C extends A {
  override type B = Seq[Int]
}

trait D extends C {
  override type B = IndexedSeq[Int]
}


// Exiting paste mode, now interpreting.

<console>:16: error: overriding type B in trait C, which equals Seq[Int];
 type B has incompatible type
         override type B = IndexedSeq[Int]
```

**Comment by mauhiz** [comment]
Oops. Refining type members means actually restraining its variance:

```
trait A {
```

  type B
}

trait C extends A {
  type B <: CharSequence
}

trait D extends C {
  type B = String
}

But yeah not sure how @provide goes in. This joke has gone a bit wrong,
sorry :)
